name: 'Terraform Plan Destroy'

on:
  push:
    branches:
    - main
    tags:
    - "destroy*"

jobs:
  terraform:
    name: 'Terraform Plan Destroy'
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_AD_CLIENT_SUBSCRIPTIONID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_CLIENT_TENANTID }}
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag' && github.ref == 'refs/tags/destroy*'
    environment: dev

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: 'Terraform Init'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.14.8
        tf_actions_subcommand: 'init'
        tf_actions_working_dir: "./Terraform"

    - name: 'Terraform Validate'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.14.8
        tf_actions_subcommand: 'validate'
        tf_actions_working_dir: "./Terraform"
        
    - name: 'Terraform Plan Destroy'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.14.8
        tf_actions_subcommand: 'plan'
        args: "-destroy"
        tf_actions_working_dir: "./Terraform"

